// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/bornehill/golang-bootcamp-2020/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// CentreRepository is an autogenerated mock type for the CentreRepository type
type CentreRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *CentreRepository) GetAll() (*[]*model.Centre, error) {
	ret := _m.Called()

	var r0 *[]*model.Centre
	if rf, ok := ret.Get(0).(func() *[]*model.Centre); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]*model.Centre)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
