// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AppRouter is an autogenerated mock type for the AppRouter type
type AppRouter struct {
	mock.Mock
}

// GetCentres provides a mock function with given fields: w, r
func (_m *AppRouter) GetCentres(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
