// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/bornehill/golang-bootcamp-2020/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// CentrePresenter is an autogenerated mock type for the CentrePresenter type
type CentrePresenter struct {
	mock.Mock
}

// JsonResponse provides a mock function with given fields: data
func (_m *CentrePresenter) JsonResponse(data *[]*model.Centre) ([]byte, error) {
	ret := _m.Called(data)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*[]*model.Centre) []byte); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*[]*model.Centre) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
